---
# tasks file for gabrielke.ansible
- name: Install add-apt-repostory
  become: yes
  apt: name=software-properties-common state=latest
  when: ansible_distribution == 'Ubuntu'

- name: Add Ansible PPA
  become: yes
  apt_repository: repo='ppa:ansible/ansible'
  when: ansible_distribution == 'Ubuntu'

- name: Install newest ansible (Debian)
  become: yes
  apt:
    name: ansible
    state: latest
    update_cache: yes
    cache_valid_time: 86400
  when: ansible_os_family == 'Debian' 

- name: Install newest ansible (RedHat)
  become: yes
  yum:
    name: ansible
    state: latest
  when: ansible_os_family == 'RedHat'
